name: staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm src/app/fuga/page.tsx
      - uses: amondnet/vercel-action@v25
