on:
  workflow_call:
    inputs:
      site:
        required: false
        type: boolean
        default: false

jobs:
  deploy-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.site == true && '' || '!src/app/fuga/*' }}
            ${{ inputs.site == true && '' || '/*' }}
          sparse-checkout-cone-mode: ${{ inputs.site == true && false || true }}
      - uses: amondnet/vercel-action@v25
        with:
          vercel-version: 33
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: ./
